config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations"}

  #root page 
  root to: 'home#index'

  #static page
  get 'home/get_started'
  get 'home/resume'
  get 'home/index'
  get 'home/test'
  get 'home/about_me'
  get 'home/contact'
  get 'posts/manage_posts'
  get 'apps/my_apps'

  get 'websites/cocoa_latte'

  
  resources :profiles
  resources :posts

  resources :apps, except: [:show]
  

end

app/models/app.rb
class App < ActiveRecord::Base

  #database schema 

=begin 
create_table "apps", force: :cascade do |t|
    t.string   "name"
    t.string   "screenshot"
    t.text     "content"
    t.string   "website"
    t.string   "repository"
    t.integer  "user_id"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
  end

=end
  
  #database relation
  belongs_to :user 

  #carrierwave uploader 
  mount_uploader :screenshot, ScreenshotUploader

  #database validation 
  validates_presence_of :name, :content, :website
end

app/models/post.rb
class Post < ActiveRecord::Base

  #database schema 

=begin 
  create_table "posts", force: :cascade do |t|
    t.string   "title"
    t.string   "image"
    t.text     "body"
    t.integer  "user_id"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.string   "slug"
  end
=end

  #database relations 
  belongs_to :user

  #database validation 
  validates_presence_of :title, :body

  #friendly_id_url 
  extend FriendlyId
  friendly_id :title, use: [:slugged, :finders]
  
  #carrierwave uplodader
  mount_uploader :image, ImageUploader

end

app/models/profile.rb
class Profile < ActiveRecord::Base

  #database schema 
=begin 
  create_table :profiles do |t|
    t.string :first_name
    t.string :last_name
    t.string :blog_title
    t.string :photo
    t.string :about_me
    t.references :user, index: true, foreign_key: true

    t.timestamps null: false
    end
=end 

  #relational database 
  belongs_to :user
  mount_uploader :photo, PhotoUploader

  #validation 
  validates_presence_of :first_name, :last_name, :blog_title, :about_me

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  #relational database 
  has_one :profile
  has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private 

  def after_sign_up_path_for(resource)
    new_profile_path
  end
end

app/controllers/apps_controller.rb
class AppsController < ApplicationController

  before_action :authenticate_user!, except: :index
  layout :visitor_or_admin?
  respond_to :html, :js


  def new 
    @app = App.new 
  end

  def create 
    @app = App.new(app_params)
    if @app.save
      redirect_to apps_path
    else
      render :new
    end
  end

  def edit 
    @app = App.find(params[:id])
  end

  def update 
    @app = App.find(params[:id])
    if @app.update_attributes(app_params)
      redirect_to apps_path
    else
      render :edit
    end
  end

  def index
    @apps = App.paginate(:page => params[:page], :per_page => 6)
  end

  def my_apps
     @apps = App.paginate(:page => params[:page], :per_page => 6)
  end

  def destroy 
    @app = App.find(params[:id])
    if @app.destroy 
      flash[:notice] = "Your app has been deleted"
    else 
      flash[:error] = "An error occured, please try again"
    end
    respond_with(@app) do |f|
      f.html { redirect_to :back }
    end
  end

  private 

  def app_params
    params.require(:app).permit(:name, :screenshot, :content, :website, :repository ) 
  end

  def visitor_or_admin?
    case action_name 
      when "index"
      "visitor"
      else
      "admin"
    end
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController 

  layout 'visitor', only: [:about_me, :contact]
  before_action :blog_has_admin_user?, only: [:index]

  def index 
  end 

  def about_me 
    @profile = Profile.first
  end

  def resume
  end

  def contact
  end

  def get_started
  end

  private 

  def blog_has_admin_user?
    if User.count == 1 
      render :index
    else
      render :get_started
    end
  end
  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController 

  layout :visitor_or_admin?
  before_action :authenticate_user!, except: [:show, :index]
  respond_to :html, :js

  def new 
    @post = Post.new
  end

  def create 
    @post = Post.new(post_params)
    if @post.save 
      redirect_to @post
    else
      render :new 
    end
  end

  def index 
    @posts = Post.paginate(:page => params[:page], :per_page => 6)
  end

  def show 
    @post = Post.friendly.find(params[:id])
  end

  def edit 
    @post = Post.friendly.find(params[:id])
  end

  def update
    @post = Post.friendly.find(params[:id])
    if @post.update_attributes(post_params)
      redirect_to @post 
    else
      render :edit 
    end
  end

  def manage_posts
   @posts = Post.paginate(:page => params[:page], :per_page => 6)
  end

  def destroy 
    @post = Post.friendly.find(params[:id])
    if @post.destroy 
      flash[:notice] = "the post has been deleted"
    else 
      flash[:error] = "An error occured, please try again"
    end
    respond_with(@post) do |f|
      f.html { redirect_to :back }
    end
  end

  private 

  def post_params
    params.require(:post).permit(:title, :image, :body, :slug)
  end

  def visitor_or_admin?
    case action_name 
      when "show", "index"
      "visitor"
      else
      "admin"
    end
  end

  


end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController 

  before_action :authenticate_user!
  layout 'admin', except: :new

  def new
    @profile = Profile.new
  end

  def show 
    @profile = Profile.find(params[:id])
  end

  def create 
    @profile = current_user.build_profile(profile_params)
    if @profile.save
      redirect_to @profile 
    else
      render :new, layout: "application"
    end
  end

  def edit 
    @profile = Profile.find(params[:id])
  end

  def update
    @profile = Profile.find(params[:id])
    if @profile.update_attributes(profile_params)
      redirect_to @profile 
    else
      render :edit 
    end
  end

  private 

  def profile_params
    params.require(:profile).permit(:first_name, :last_name, :blog_title, :photo, :about_me)
  end
  
end 

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  before_action :single_user_registered?
  
  protected

  def single_user_registered?
    if ((User.count == 1) & (user_signed_in?))
      redirect_to root_path
    elsif User.count == 1
      redirect_to new_user_session_path
    end  
  end

  def after_sign_up_path_for(resource)
    new_profile_path
  end

end

app/controllers/websites_controller.rb
class WebsitesController < ApplicationController 

 def cocoa_latte
 end
  
  

end

app/helpers/application_helper.rb
module ApplicationHelper

  class HTMLwithPygments < Redcarpet::Render::HTML
    def block_code(code, language)
      Pygments.highlight(code, lexer: language)
    end
  end

  def markdown(content)
    renderer = HTMLwithPygments.new(hard_wrap: true, filter_html: true)
    options = { 
      autolink: true, 
      no_intra_emphasis: true, 
      disable_indented_code_blocks: true, 
      fenced_code_blocks: true, 
      lax_html_blocks: true, 
      strikethrough: true, 
      superscript: true, 
    }
    preserve(Redcarpet::Markdown.new(renderer, options).render(content).html_safe)
  end

  def active_link(path)
    'active_link' if current_page?(path)
  end

  def root_active_link(path)
    'active_link' if (current_page?(path) || current_page?(posts_path))   
  end

end

app/views/apps/_form.html.haml
= simple_form_for @app do |f| 
  = f.input :name 
  = f.input :screenshot 
  = f.input :content 
  = f.input :website 
  = f.input :repository 
  = f.button :submit 

app/views/apps/destroy.js.haml
- if @app.destroyed?
  $('#app_' +#{@app.id}).hide();
- else
  $('#app_' +#{@app.id}).prepend("
  .alert.alert-danger>= flash[:error]
  ");

app/views/apps/edit.html.haml
= render 'form'

app/views/apps/index.html.haml
.col-md-9.col-xs-12.col-centered.apps-wrapper
  - @apps.each do |app|
    %ul.app-details.list-unstyled
      %li
        %h2.app-title.text-center
          = app.name

      .app-image-wrapper
        %li.text-center
          = image_tag(app.screenshot_url, class: "screenshot-app" )
      .app-description.col-md-9.col-centered.text-center
        %li.app-content
          = app.content
        %li
          = link_to 'Website', "//#{app.website}"
        - if app.repository.present?
          %li
            = link_to 'Github Repository', "//#{app.repository}"

app/views/apps/my_apps.html.haml
.col-md-9.col-xs-12.col-centered.projects-wrapper
  - if @apps.present?
    - @apps.each do |app|
      %ul.project-details.list-unstyled{:id => dom_id(app)}
        %li
          %h2.title-project.text-center
            = app.name

        .project-image-wrapper
          %li.text-center
            = image_tag(app.screenshot_url, class: "screenshot-app" )
        .project_description.col-md-9.col-centered.text-center
          %li.project-content
            = app.content
          %li
            = link_to 'Website', "http://#{app.website}"
          %li
            = link_to 'Github Repository', app.repository
          %li
            = link_to 'Edit app info', edit_app_path(app.id)
          %li
            = link_to 'Delete app', app, method: :delete,remote: true, data: {confirm: 'Are Sure about that ?'}
          %li
            = link_to 'New app', new_app_path 
  - else 
    = link_to 'New app', new_app_path 

app/views/apps/new.html.haml
= render 'form'

app/views/home/about_me.html.haml
%section.content-about-me.col-md-8.col-centered
  %p.first-code
    2.1.0 :001 > puts "Hi there,  my name is philippe AKA"
    
  %p
    = markdown @profile.about_me 

  

app/views/home/contact.html.haml
.contact-wrapper.col-md-9.col-centered
  .contact-information.col-md-11.col-centered.text-center
    %h3 Please do not hesitate to contact me at akaphilippe@outlook.com
    %h4 follow me or contact me through my social media accounts :
    .social-media
      %ul.list_unstyled
        %li{:style => "display:inline;"}
          %a.social-media-icon{:href => "https://github.com/philiboua"}
            %span.fa.fa-github
              %p GitHub
        %li{:style => "display:inline;"}
          %a.social-media-icon{:href => "https://ca.linkedin.com/in/philippeaka"}
            %span.fa.fa-linkedin
              %p linkedin
        %li{:style => "display:inline;"}
          %a.social-media-icon{:href => "https://angel.co/akka-philippe"}
            %span.fa.fa-angellist
              %p AngelList

app/views/home/get_started.html.haml
.blog-wrapper 
  .container
    .row 
      .col-xs-12
        = link_to 'Start your blog', new_user_registration_path, class: 'btn registration-button'

app/views/home/index.html.haml
%body.body-wp
  #particles-js.p-wrapper
    #home.homepage-hero
      .container-content
        .flexbox-column
          .header-wp

            .social-media
              %a.link.social-media-icon{:href => "https://www.linkedin.com/in/philippeaka/", :target => "_blank"} 
              %a.link.social-media-icon{:href => "https://github.com/philiboua/", :target => "_blank"} 
              %a.behance.link.social-media-icon{:href => "#"} 
              %a.dribble.link.social-media-icon{:href => "#"} 
            .menu-wp.w-hidden-main{"data-ix" => "display-menu"}
              .html-embed.w-embed
                #menu-button.menu
                  %span.menu-global.menu-top
                  %span.menu-global.menu-middle
                  %span.menu-global.menu-bottom
            .menu-pc.w-hidden-medium.w-hidden-small.w-hidden-tiny
              = link_to "ABOUT", "#about", class: " menu-pc-link hvr-bob"
              = link_to "SKILLS", "#skills", class: " hvr-bob  menu-pc-link"
              = link_to "WORK", "#work", class: " hvr-bob menu-pc-link"
              = link_to "BLOG", "https://medium.com/philippeaka",:target => "_blank", class: " hvr-bob menu-pc-link"
              = link_to "CONTACT", "#contact", class: "scroll-top  hvr-bob menu-pc-link"

        .homepage-content
          %h1.title-author-blog
            PHILIPPE
            %span.text-span
              %span AKA
              %span.function-author WEB DEVELOPER
          %h1.heading Web developer / Web designer



  #about.section
    .container-content
      .flexbox.flexbox-column
        %h1.title-section About Me
        %p.section-text
          %span.text-span-3> Hello
          ,
          %br/
          %span.text-span-4 My name is Philippe AKA. I am a full stack developer based in Toronto, Canada. I have gained knowledge and experience writing clean semantic code, responsive web design and developed a strong interest to learn more about UX design. My interest in coding developed as a result of a passion for startups and what we can achieve with technology.


  #skills.section
    .container-content
      .flexbox.flexbox-column
        %h1.title-section skills

        .skills-box
          .skills-item{"data-ix" => "appear-skill-item-2"}
            .w-embed
              %i.devicon-html5-plain-wordmark
          .skills-item{"data-ix" => "appear-skill-item-1"}
            .w-embed
              %i.devicon-css3-plain-wordmark
          .skills-item{"data-ix" => "appear-skill-item-2"}
            .w-embed
              %i.devicon-bootstrap-plain-wordmark
          .skills-item{"data-ix" => "appear-skill-item-2"}
            .w-embed
              %i.devicon-jquery-plain-wordmark
          .skills-item{"data-ix" => "appear-skill-item-2"}
            .w-embed
              %i.devicon-javascript-plain
          .skills-item{"data-ix" => "appear-skill-item-2"}
            .w-embed
              %i.devicon-sass-original
          .skills-item{"data-ix" => "appear-skill-item-2"}
            .w-embed
              %i.devicon-git-plain-wordmark
          .skills-item{"data-ix" => "appear-skill-item-2"}
            .w-embed
              %i.devicon-github-plain-wordmark
          .skills-item{"data-ix" => "appear-skill-item-2"}
            .w-embed
              %i.devicon-bitbucket-plain-wordmark
          .skills-item{"data-ix" => "appear-skill-item-2"}
            .w-embed
              %i.devicon-heroku-original-wordmark
          .skills-item{"data-ix" => "appear-skill-item-2"}
            .w-embed
              %i.devicon-ruby-plain-wordmark
          .skills-item{"data-ix" => "appear-skill-item-2"}
            .w-embed
              %i.devicon-rails-plain-wordmark


  #work.section
    .container-content
      .flexbox.flexbox-column
        %h1.title-section work

        .mobile-box-project-wp

          .work-box-mobile
            = image_tag('placeit.png',  class: 'image-2', style: 'width: 543;')
            .work-text-mobile
              %h1.heading-2 Agence VS
              %p.work-paragraph AGENCE VS is a marketing and business agency. AGENCE VS help their client in Ivory Coast and Canada to improve their value proposition and increase their sales.
              .work-link-wp
                %a.button-link.w-button{:href => "http://www.lagencevs.com/", :target => "_blank"} Live Website
                %a.button-link.project-link.w-button{:href => "#"} Project details

          .work-box-mobile
            = image_tag('paad-agency.png',  class: 'image-2', style: 'width: 543;')
            .work-text-mobile
              %h1.heading-2 Paad
              %p.work-paragraph Paad is a digital Agency for small businesses. We help small businesses to increase their sales through websites or social media channels.
              .work-link-wp
                %a.button-link.w-button{:href => "http://paad.agency/works-masonry.html", :target => "_blank"} Live Website
                %a.button-link.project-link.w-button{:href => "#"} Project details

          .work-box-mobile
            = image_tag('placeit-1.png',  class: 'image-2', style: 'width: 543;')
            .work-text-mobile
              %h1.heading-2 Reccrut
              %p.work-paragraph Reccrut is a web application for startups. Recruiters can post jobs and filter best candidates through video interviews. Job seekers can create a short video to pitch themselves.
              .work-link-wp
                %a.button-link.w-button{:href => "https://www.reccrut.com/", :target => "_blank"} Live Website
                %a.button-link.project-link.w-button{:href => "#"} Project details

          .work-box-mobile
            = image_tag('aylie_screenshot_mockup.png',  class: 'image-2', style: 'width: 543;')
            .work-text-mobile
              %h1.heading-2 Ayelie
              %p.work-paragraph Ayelie is a new cosmetic brand for curly hair. The website is still in progress but I am truly amazed by the logo done by my partner Dominique Amangoua.
              .work-link-wp
                %a.button-link.w-button{:href => "http://ayelieproject.webflow.io/", :target => "_blank"} Live Website
                %a.button-link.project-link.w-button{:href => "#"} Project details

          .work-box-mobile
            = image_tag('Cocoa-Latte--webscreen.png',  class: 'image-2', style: 'width: 543;')
            .work-text-mobile
              %h1.heading-2 Cocoa Latte
              %p.work-paragraph Drogba is the most valuable soccer player in Ivory Coast in my opinion. Like the Nike battleground in France in 2002, I am pretty sure there will be a Drogba Cup soon in Ivory Coast.
              .work-link-wp
                %a.button-link.w-button{:href => "http://template-cocoa-latte.webflow.io/", :target => "_blank"} Live Website
                %a.button-link.project-link.w-button{:href => "#"} Project details

          .work-box-mobile
            = image_tag('placeit_1.png',  class: 'image-2', style: 'width: 543;')
            .work-text-mobile
              %h1.heading-2 Drogba Cup
              %p.work-paragraph Drogba is the most valuable soccer player in Ivory Coast in my opinion. Like the Nike battleground in France in 2002, I am pretty sure there will be a Drogba Cup soon in Ivory Coast.
              .work-link-wp
                %a.button-link.w-button{:href => "http://drogbacup.webflow.io/", :target => "_blank"} Live Website
                %a.button-link.project-link.w-button{:href => "#"} Project details


  #contact.section.section-contact
    .container-content
      .flexbox.flexbox-column
        %h1.title-section contact
        


        .contact-form-submit
          .w-embed
            %form{:action => "http://formspree.io/philippeaka@outlook.com", :method => "POST"}
              %article
                %input#name.border-form{:name => "name", :placeholder => "Your name", :required => "", :size => "50", :type => "text"}/
              %article
                %input#email.border-form{:name => "email", :placeholder => "Your email", :required => "", :size => "50", :type => "text"}/
              %article
                %textarea#msg.border-form{:cols => "40", :name => "message", :placeholder => "Please write your message", :required => "", :rows => "8", :size => "50"}
                .btn-wrap.text-left
                  %button#submit.btn-submit{:name => "submit", :type => "submit"} Submit

            


        .footer-social-media
          .social-media
            %a.link.social-media-icon{:href => "https://www.linkedin.com/in/philippeaka/", :target => "_blank"} 
            %a.link.social-media-icon{:href => "https://github.com/philiboua/", :target => "_blank"} 
            %a.behance.link.social-media-icon{:href => "#"} 
            %a.dribble.link.social-media-icon{:href => "#"} 



  .menu-container
    %a.close-menu.w-inline-block{:href => "#"}
    %h1.title-menu Pa
    %a.menu-link{:href => "#about"} about
    %a.menu-link{:href => "#skills"} SKILLS
    %a.menu-link{:href => "#work"} WORK
    %a.blog-link{:href => "https://medium.com/philippeaka", :target => "_blank"} BLOG
    %a.menu-link{:href => "#contact"} CONTACT
  .go-up
  

%script{:src => "https://cdn.jsdelivr.net/particles.js/2.0.0/particles.min.js"}


:javascript
  particlesJS("particles-js", {"particles":{"number":{"value":120,"density":{"enable":true,"value_area":2000}},"color":{"value":"#a3fdf6"},"shape":{"type":"circle","stroke":{"width":0,"color":"#000000"},"polygon":{"nb_sides":5},"image":{"src":"img/github.svg","width":100,"height":100}},"opacity":{"value":0.5,"random":false,"anim":{"enable":false,"speed":1,"opacity_min":0.1,"sync":false}},"size":{"value":3,"random":true,"anim":{"enable":false,"speed":20,"size_min":0.1,"sync":false}},"line_linked":{"enable":false,"distance":150,"color":"#a3fdf6","opacity":0,"width":1},"move":{"enable":true,"speed":2,"direction":"none","random":false,"straight":true,"out_mode":"out","bounce":false,"attract":{"enable":true,"rotateX":600,"rotateY":1200}}},"interactivity":{"detect_on":"canvas","events":{"onhover":{"enable":false,"mode":"repulse"},"onclick":{"enable":true,"mode":"push"},"resize":true},"modes":{"grab":{"distance":400,"line_linked":{"opacity":1}},"bubble":{"distance":400,"size":40,"duration":2,"opacity":8,"speed":3},"repulse":{"distance":200,"duration":0.4},"push":{"particles_nb":4},"remove":{"particles_nb":2}}},"retina_detect":true});var count_particles, stats, update; stats = new Stats; stats.setMode(0); stats.domElement.style.position = 'absolute'; stats.domElement.style.left = '0px'; stats.domElement.style.top = '0px'; document.body.appendChild(stats.domElement); count_particles = document.querySelector('.js-count-particles'); update = function() { stats.begin(); stats.end(); if (window.pJSDom[0].pJS.particles && window.pJSDom[0].pJS.particles.array) { count_particles.innerText = window.pJSDom[0].pJS.particles.array.length; } requestAnimationFrame(update); }; requestAnimationFrame(update);;


:javascript
  $(document).on('click', '.menu-link', function(event){
    event.preventDefault();

    $('html, body').animate({
        scrollTop: $( $.attr(this, 'href') ).offset().top
    }, 1000);
    $( ".menu-wp" ).trigger( "click" )
  });

app/views/home/resume.html.haml
.pageBg
  = render 'shared/header'
  
      
    

app/views/layouts/admin.html.haml
!!!
%html
  %head
    %meta{:content => "width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no", :name => "viewport"}/
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %link{:href => "https://cdn.rawgit.com/konpa/devicon/master/devicon.min.css", :rel => "stylesheet"}/
    %link{:href => "https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.5.2/animate.min.css", :rel => "stylesheet"}/
    %link{:href => "https://fonts.googleapis.com/css?family=Droid+Serif", :rel => "stylesheet"}/
    %title Philippe AKA | Full stack developer
    = favicon_link_tag 'logo-ico.ico'
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  
  %body
    .admin-destock-nav
      %ul.list-unstyled
        %li.text-center
          .nav-item
            = link_to profile_path(Profile.first.id) do  
              %i.fa.fa-user.fa-2x.logo-item 
              Profile
        %li.text-center
          .nav-item
            = link_to posts_manage_posts_path do  
              %i.fa.fa-newspaper-o.fa-2x.logo-item 
              Posts
        %li.text-center
          .nav-item
            = link_to apps_my_apps_path do  
              %i.fa.fa-laptop.fa-2x.logo-item 
              Apps  
        %li.text-center
          .nav-item
            = link_to root_path do  
              %i.fa.fa-eye.fa-2x.logo-item 
              Visitor Mode

    .admin-mobile-nav
      %nav.navbar.navbar-fixed-top.admin-custom-nav{:role => "navigation"}
        .navbar-header
          %button.navbar-toggle{"data-target" => "#navbarCollapse", "data-toggle" => "collapse", :type => "button"}
            %span.sr-only Toggle navigation
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.navbar-brand{:href => '/articles'} Blog Admin
        #navbarCollapse.collapse.navbar-collapse
          %ul.nav.navbar-nav
            %li
              = link_to "My Profile", profile_path(Profile.first.id)
            %li
              = link_to "My Posts", posts_manage_posts_path
            %li
              = link_to "My apps", apps_my_apps_path
            %li
              = link_to "Visitor mode", root_path
            %li
              - if user_signed_in?
                = link_to 'Log out', destroy_user_session_path, method: :delete

    .admin-page-wrapper 
      .container 
        .row
          .col-xs-12.col-md-8.col-centered
            

          
            = yield

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no", :name => "viewport"}/
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %link{:href => "https://cdn.rawgit.com/konpa/devicon/master/devicon.min.css", :rel => "stylesheet"}/
    %link{:href => "https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.5.2/animate.min.css", :rel => "stylesheet"}/


    %link{:href => "https://fonts.googleapis.com/css?family=Droid+Serif", :rel => "stylesheet"}/
    %title Philippe AKA | Full stack developer
    = favicon_link_tag 'logo-ico.ico'
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  
  %body
    
    = yield
   

app/views/posts/_form.html.haml
= simple_form_for @post do |f|
  = f.input :title 
  = f.input :image 
  = f.input :body,:input_html => {:rows => 18, style: 'max-width:100%; height:100%;'}
  = f.button :submit

app/views/posts/destroy.js.haml
- if @post.destroyed?
  $('#post_' +#{@post.id}).hide();
- else
  $('#post_' +#{@post.id}).prepend("
  .alert.alert-danger>= flash[:error]
  ");

app/views/posts/edit.html.haml
%h1.text-center 
  Edit Post
  
= render 'form'

app/views/posts/index.html.haml
.pageBg
  = render 'shared/header'
  .col-md-8.col-centered
    - if @posts.present?
      - @posts.each do |post| 
        .article-preview
          - if post.image.present?
            = image_tag(post.image_url, class: 'post-image')
          %h3.title-article-preview
            = link_to "#{post.title}", post_path(post.slug)
          %p
            = markdown post.body.first(210) + "..."
          = link_to 'read more',post_path(post.slug)
      .post-pagination.text-center
        = will_paginate @posts, renderer: BootstrapPagination::Rails

app/views/posts/manage_posts.html.haml
%h1.text-center 
  Posts published 

- if @posts.present?
  - @posts.each do |post|
    .col-md-6.col-xs-4{:id => dom_id(post)}
      %h4.post-title
        = post.title
      .post-links
        = link_to 'view post', post_path(post.slug), class: 'btn btn-default full-width'
        = link_to 'edit post', edit_post_path(post.slug), class: 'btn btn-default full-width'
        = link_to 'delete post', post, method: :delete,remote: true, data: {confirm: 'Are Sure about that ?'}, class: 'btn btn-default full-width'
  .col-md-6.col-xs-4
    %h3.new-post
      = link_to 'write a new post', new_post_path, class: 'btn btn-default'
  .post-pagination.col-md-12.text-center 
    = will_paginate @posts, renderer: BootstrapPagination::Rails
- else 
  = link_to 'write a new post', new_post_path,  class: 'btn btn-default'    

app/views/profiles/show.html.haml
= @profile.first_name 
= @profile.last_name 
= @profile.blog_title
= @profile.photo 
= @profile.about_me 

= link_to 'edit profile', edit_profile_path(@profile.id)